// 流程表单数据模型
export default {
    // 立项申请表单数据模型(内部/企业) (含内置数据)
    applyPorjectForm: {
        applyReason: "<p><em>应从以下6方面阐述：</em></p><p><em>1)项目的功能和应用介绍；</em></p> <p><em>2) 发现的问题或不足；</em></p> <p><em>3) 是否有相关的课题，及该课题的进度和成果；</em></p> <p><em>4)相关的国内外标准现状，若有，需列出已知的相关标准；</em></p> <p><em>5) 分析说明现有标准不能满足要求；</em></p> <p><em>6) 已经完成的相关工作及制定标准已具备的条件。</em></p>", // 申请理由
        commitStatus: null, // 提交状态 1：暂存，2：提交
        internationalStandardNameAdopted: null, // 国际标准采标名称
        internationalStandardNoAdopted: null, // 国际标准采标号
        keyTechniqueContent: "<p><em>必须包含以下内容：</em></p> <p><em>1)适用范围说明；</em></p> <p><em>标准内容大纲（应包含重点技术内容）。</em></p>", // 关键技术内容
        projectName: null, // 项目名称
        mainEditorIds: null, // 主要起草人 多个用逗号分隔
        projectType: null, // 项目类型（1:企业标准立项；2:外部标准立项；3:企业标准特殊立项）
        scheduledEndTime: null, // 计划结束时间
        scheduledEndTime: null, // 计划开始时间
        scpStdComment: { // 编制说明
            bigIssues: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", //重大分歧意见
            internationStandardAdopt: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", // 采标情况
            keyIndicator: "<p>1.<span style='background-color: yellow;'>××××</span></p><p>2.<span style='background-color: yellow;'>××××</span></p><p>3.<span style='background-color: yellow;'>××××</span></p><p><span style='background-color: yellow;'>……</span></p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>制定标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键指标或要求（不少于3个）的制定依据、具体指标说明</em></p><p>	<em style='background-color: lime;'>示例：在对高速铁路CZ道岔尖轨、心轨跟端性能要求及试验方法进行充分调研、试验验证的基础上，对尖轨、心轨跟端疲劳试验方法、载荷值做出了规定，提出了经2×10</em><sup style='background-color: lime;'><em>6</em></sup><em style='background-color: lime;'>次循环加载后不应断裂的要求。</em></p><p>	</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>修订标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键技术性修订（不少于3个）的修订理由和依据，包括原标准错误或不适用要求的修订。</em></p><p>	<em style='background-color: lime;'>示例1：依据《铁路大型养路机械 通用技术条件》（GB/T 25337-2018）、《铁路大型养路机械 检查与试验方法》（GB/T 25336-2018）等国家标准，结合钢轨铣磨车在我国铁路线路养护维修中的实际应用经验，提出了钢轨铣磨车最大作业速度应大于或等于1.2km/h、一遍作业轨面最大铣削深度应大于或等于1.5mm，轨侧最大铣削深度应大于或等于3 mm的技术要求，以及相应的检验方法。</em></p><p>	<em style='background-color: lime;'>示例2：根据交流传动电力机车网侧谐波分布特点，在对各型交流传动机车等效干扰电流、综合电流畸变率计算方法充分调研分析的基础上，修改了等效干扰电流和综合电流畸变率计算中的谐波电流次数，其中等效干扰电流由计算至30次谐波修改为60次谐波，综合电流畸变率由计算至30次谐波修改为100次谐波。</em></p><p>	<em style='background-color: lime;'>示例3：参考《铁路应用 轮对和转向架 车轮 产品要求》（EN 13262:2004），增加了车轮疲劳性能要求“辐板径向试验应力为±240 N/mm</em><sup style='background-color: lime;'><em>2</em></sup><em style='background-color: lime;'>、经过10</em><sup style='background-color: lime;'><em>7</em></sup><em style='background-color: lime;'>次循环后车轮不应产生裂纹”以及相应的试验方法。</em></p><p><em style='background-color: lime;'>示例4：在总结分析我国混凝土桥、钢梁桥钢轨伸缩调节器的应用经验基础上，本标准提出了客货共线铁路钢轨伸缩调节器基本轨伸缩阻力不应大于50kN、尖轨伸缩阻力不应小于100kN，既能保证基本轨伸缩自如，又能保证调节器轨距变化不超过允许值。</em></p>", // 关键指标确定
            mainContent: '<p>1.1<u>本文件</u>规定了<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致，列出具体内容）</em>；适用于<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致）</em>。</p><p>1.2<u>本文件</u><span style="background-color: yellow;">依据××××《××××</span><em style="background-color: lime;">（国际标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（国家标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（行业标准编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: yellow;">，参考</em><span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（其他规范性文件编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: lime;">（例如铁总暂行技术条件、国外标准）</em><span style="background-color: yellow;">等技术规范</span><em style="background-color: yellow;">，</em>结合应用实际编制。</p><p>	<u>本文件</u>与<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》</span>/<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）' + '</em><span style="background-color: yellow;">》</span>相比，重要技术差异见表1。<em style="background-color: lime;">（如有相关标准性技术文件/铁总企业标准）</em></p><p class="ql-align-center">表1 与<span style="background-color: yellow;">××××(</span><em style="background-color: lime;">标准性技术文件或企业标准<u>名称</u>)</em>的重要技术差异</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">标准性技术文件/</td><td data-row="1" class="ql-align-center"><span style="background-color: yellow;">铁总企业标准</span></td><td data-row="1" class="ql-align-center">本文件</td><td data-row="1" class="ql-align-center">说明</td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: ' +
                'lime;">（文件章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本标准章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（技术差异说明）</em></td><td data-row="2"><br></td></tr><tr><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3"><br></td></tr><tr><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6"' +
                'class="ql-align-center"><br></td><td data-row="6"><br></td></tr></tbody></table><p>经起草组研究分析，没有与本文件相关联的标准性技术文件及铁总企业标准。<em style="background-color: lime;">（如无相关标准性技术文件/铁总企业标准）</em></p><p>1.3经起草组分析研究，<span style="color: black;">与本文件主要技术内容有关联的</span>现行国家标准、行业标准的关联<span style="color: black;">关系及后续工作建议见表2。</span><em style="color: black; background-color: lime;">（如有相关联的国标、行标）</em></p><p><br></p><p class="ql-align-center">表2 《<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本文件名称）</em>》相关标准评估表</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">被评估标准编号及名称</td><td data-row="1" class="ql-align-center">关联条款</td><td data-row="1" class="ql-align-center">关联性分析</td><td data-row="1" class="ql-align-center">本文件条款的合理性分析</td><td data-row="1" class="ql-align-center">后续工作建议</td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（标准编号）</em><span style="background-color: yellow;">《××××</span><em style="background-color: lime;">（标准名称）</em><span style="background-color: yellow;">》</span></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style=" ' +
                'background-color: lime;">（标准编号）</em>的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>与本文件的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>存在关联</td><td data-row="2"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（关联关系说明）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（条款合理性分析）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（后续工作建议）</em></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td></tr><tr><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3" class="ql-align-center"><em style="background-color: lime;">1</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010《轨道交通 机车车辆牵引变压器和电抗器》</em></td><td data-row="3"><em' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10与本标准第5章存在关联</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10是变压器部件型式试验要求，而本标准第5章包含的是变压器撞车后电力机车作为对象进行的整车温升试验</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准中要求整车试验前完成相关零部件及子系统的型式试验，并应向整车试验单位提交试验报告结果。一般涉及牵引变压器温升的型式试验，即依据GB/T 25120-2010进行，因此，GB/T 25120-2010是本标准试验实施的基础，本标准规定了整车温升试验的工况要求，同时考虑到整车试验的可操作性，可以以车载传感器记录的变压器油温作为参考</em></td><td data-row="3"><em ' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准与GB/T 25120</em></td><td data-row="3"><em style="background-color: lime;">-2010无冲突，GB/T 25120-2010条款无须更改</em></td></tr><tr><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td></tr><tr><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td></tr><tr><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8" class="ql-align-' +
                'center"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td></tr><tr><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td></tr></tbody></table><p><br></p><p>经起草组分析研究，没有与本标准/部分主要技术内容相关联的现行国家标准、行业标准。<em style="background-color: lime;">（如无相关联的国标、行标）</em></p>', //  主要内容
            otherItemsToBeComment: "<p><em style='background-color: lime;'>根据实际情况编写。</em></p>", // 其他应予说明事项
            scplatPrinciple: "<p>1.1&nbsp;标准格式统一、规范，符合<span style='background-color: fuchsia;'>GB/T 1.1—2020</span>要求。</p><p>1.2&nbsp;标准内容符合<span style='color: black;'>统一性、协调性、适用性、一致性、规范性要</span>求。</p><p>1.3&nbsp;标准技术内容<span style='color: black;'>安全可靠、成熟稳定、经</span>济适用、科学先进、节能环保。</p><p>1.4&nbsp;标准实施后有利于提高铁路产品质量、保障运输安全，符合铁路行业发展需求。</p>", // 编制原则
            workBrief: "<p><strong>1.1&nbsp;编制依据</strong></p><p>	根据<span style='background-color: yellow;'>XXXXX</span>通知的要求，由<span style='background-color: fuchsia;'>技术中心科技管理部归口</span>，<span style='color: black;'>并</span>由<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）、</em><span " +
                "style='background-color: yellow;'>……</span>共同起草。</p><p>	<u>本文件</u>为首次制定。<em style='background-color: lime;'>（新制定标准应有本段内容）</em></p><p>	<u>本文件</u>是对<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准编号和名称，编号加年代号）</em>的修订。/<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准1编号和名称）、</em><span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准2编号和名称）、</em><span style='background-color: yellow;'>……</span>的整合修订。<em style='background-color: lime;'>（修订标准应根据实际情况确定本段内容）</em></p><p><strong>1.2&nbsp;制修订本标准的必要性</strong></p><p>	<span style='background-color: yellow;'>……</span>。<em style='background-color: lime;'>（此" + "处给出制修订本标准必要性的说明）</em></p><p><strong>1.3&nbsp;编制过程</strong></p><p>	在<u>本文件</u>的编制过程中，完成了大量的基础研究和编写工作，并邀请了国内和铁路行业相关领域的专家进行了技术审查，确保了标准的规范性和权威性。<u>本文件</u>编制过程概要如下<em style='background-color: lime;'><u>(适用于报批稿)</u></em>：</p><p>	<em style='background-color: lime;'>（编制过程说明至少包括征求意见稿、送审稿、审查会会议纪要、报批稿等四个阶段，根据实际情况增加工作组、送审二稿等阶段）</em></p><p>	（1）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>工作大纲、草案阶段，如有］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em " +
                "style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，形成了工作大纲和<u>本文件</u>的草案稿。</p><p>	（2）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段</em><span style='background-color: lime;'>，</span><em style='background-color: lime;'>有工作大纲和草案阶段的编写本段内容］</em>标准起草组<span style='color: black;'>对前期工作和标准草案深入讨论研究后，</" + "span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段，没有工作大纲和草案阶段的编写本段内容］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，在对<span style='color: black;'>前期工作深入讨论研究后，</span><span style='background-color: yellow;'>××××</span>年" +
                "<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	（3）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿阶段</em><span style='background-color: lime;'>］</span>征求意见过程中，共收到<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（回函单位数量）</em>个单位的回函，其中有反馈意见的单位<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（反馈意见单位数量）</em>个，收到意见<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（意见条数）</em>条。标准起草组对回函的意见进行研究和讨论，逐条进行了处理，对<u>本文件</u>进行修改完善，并组织相关单位进行讨论，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了本文件的送审稿并发送<span style='background-color: fuchsia;'>项目组</span>。</p><p>	（4）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。审查会议无意见分歧，会议通过了<u>本文件</u>的审查。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: " +
                "yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。除<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等技术内容外，审查会议无意见分歧，会议要求起草组对<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（技术问题）</em>等技术内容进一步研究。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	（5）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容，如有更多送审稿别，参考此段增加内容</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的送审二稿，并于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月召开了送审二稿审查会。审查会议无意见分歧，会议通过了送审二稿的审查，<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿如未通过，根据情况增加送审N稿内容</em><span style='background-color: lime;'>］</span></p><p>	（6）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>报批稿阶段</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的报批稿并发送<span style='background-color: fuchsia;'>项目组，由项目组</span>上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>。</p>", // 工作简况
        },
        scplatMode: null, // 制修订模式（0:新编；1:修订）
        stdDraftUrl: null, // 草案稿url地址
        infoPublishId: null, // 信息发布id
        oldStdNo: null, // 修订标准编号 
        oldStdId: null, // 修订标准ID
        stdDraftDeadline: null, //草案稿计划完成时间
        stdForAdviceDeadline: null, // 征求意见稿计划完成时间
        stdForApprovalDeadline: null, // 报批稿计划完成时间
        stdForReviewDeadline: null, // 送审稿计划完成时间
        stdMultiAggreementDeadline: null, // 会签计划完成时间

    },
    // 特使立项申请表单数据模型(内部/企业) (含内置数据)
    applySpecialPorjectForm: {
        applyReason: "<p><em>应从以下6方面阐述：</em></p><p><em>1)项目的功能和应用介绍；</em></p> <p><em>2) 发现的问题或不足；</em></p> <p><em>3) 是否有相关的课题，及该课题的进度和成果；</em></p> <p><em>4)相关的国内外标准现状，若有，需列出已知的相关标准；</em></p> <p><em>5) 分析说明现有标准不能满足要求；</em></p> <p><em>6) 已经完成的相关工作及制定标准已具备的条件。</em></p>", // 申请理由
        interfacePersonIds: null, // 标准化接口人
        specialApplyReason: "", // 申请理由
        internationalStandardNameAdopted: null, // 国际标准采标名称
        internationalStandardNoAdopted: null, // 国际标准采标号
        keyTechniqueContent: "<p><em>必须包含以下内容：</em></p> <p><em>1)适用范围说明；</em></p> <p><em>标准内容大纲（应包含重点技术内容）。</em></p>", // 关键技术内容
        projectName: null, // 项目名称
        mainEditorIds: null, // 主要起草人 多个用逗号分隔
        projectType: null, // 项目类型（1:企业标准立项；2:外部标准立项；3:企业标准特殊立项）
        scheduledEndTime: null, // 计划结束时间
        scheduledEndTime: null, // 计划开始时间
        scpStdComment: { // 编制说明
            bigIssues: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", //重大分歧意见
            internationStandardAdopt: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", // 采标情况
            keyIndicator: "<p>1.<span style='background-color: yellow;'>××××</span></p><p>2.<span style='background-color: yellow;'>××××</span></p><p>3.<span style='background-color: yellow;'>××××</span></p><p><span style='background-color: yellow;'>……</span></p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>制定标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键指标或要求（不少于3个）的制定依据、具体指标说明</em></p><p>	<em style='background-color: lime;'>示例：在对高速铁路CZ道岔尖轨、心轨跟端性能要求及试验方法进行充分调研、试验验证的基础上，对尖轨、心轨跟端疲劳试验方法、载荷值做出了规定，提出了经2×10</em><sup style='background-color: lime;'><em>6</em></sup><em style='background-color: lime;'>次循环加载后不应断裂的要求。</em></p><p>	</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>修订标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键技术性修订（不少于3个）的修订理由和依据，包括原标准错误或不适用要求的修订。</em></p><p>	<em style='background-color: lime;'>示例1：依据《铁路大型养路机械 通用技术条件》（GB/T 25337-2018）、《铁路大型养路机械 检查与试验方法》（GB/T 25336-2018）等国家标准，结合钢轨铣磨车在我国铁路线路养护维修中的实际应用经验，提出了钢轨铣磨车最大作业速度应大于或等于1.2km/h、一遍作业轨面最大铣削深度应大于或等于1.5mm，轨侧最大铣削深度应大于或等于3 mm的技术要求，以及相应的检验方法。</em></p><p>	<em style='background-color: lime;'>示例2：根据交流传动电力机车网侧谐波分布特点，在对各型交流传动机车等效干扰电流、综合电流畸变率计算方法充分调研分析的基础上，修改了等效干扰电流和综合电流畸变率计算中的谐波电流次数，其中等效干扰电流由计算至30次谐波修改为60次谐波，综合电流畸变率由计算至30次谐波修改为100次谐波。</em></p><p>	<em style='background-color: lime;'>示例3：参考《铁路应用 轮对和转向架 车轮 产品要求》（EN 13262:2004），增加了车轮疲劳性能要求“辐板径向试验应力为±240 N/mm</em><sup style='background-color: lime;'><em>2</em></sup><em style='background-color: lime;'>、经过10</em><sup style='background-color: lime;'><em>7</em></sup><em style='background-color: lime;'>次循环后车轮不应产生裂纹”以及相应的试验方法。</em></p><p><em style='background-color: lime;'>示例4：在总结分析我国混凝土桥、钢梁桥钢轨伸缩调节器的应用经验基础上，本标准提出了客货共线铁路钢轨伸缩调节器基本轨伸缩阻力不应大于50kN、尖轨伸缩阻力不应小于100kN，既能保证基本轨伸缩自如，又能保证调节器轨距变化不超过允许值。</em></p>", // 关键指标确定
            mainContent: '<p>1.1<u>本文件</u>规定了<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致，列出具体内容）</em>；适用于<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致）</em>。</p><p>1.2<u>本文件</u><span style="background-color: yellow;">依据××××《××××</span><em style="background-color: lime;">（国际标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（国家标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（行业标准编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: yellow;">，参考</em><span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（其他规范性文件编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: lime;">（例如铁总暂行技术条件、国外标准）</em><span style="background-color: yellow;">等技术规范</span><em style="background-color: yellow;">，</em>结合应用实际编制。</p><p>	<u>本文件</u>与<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》</span>/<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）' + '</em><span style="background-color: yellow;">》</span>相比，重要技术差异见表1。<em style="background-color: lime;">（如有相关标准性技术文件/铁总企业标准）</em></p><p class="ql-align-center">表1 与<span style="background-color: yellow;">××××(</span><em style="background-color: lime;">标准性技术文件或企业标准<u>名称</u>)</em>的重要技术差异</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">标准性技术文件/</td><td data-row="1" class="ql-align-center"><span style="background-color: yellow;">铁总企业标准</span></td><td data-row="1" class="ql-align-center">本文件</td><td data-row="1" class="ql-align-center">说明</td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: ' +
                'lime;">（文件章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本标准章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（技术差异说明）</em></td><td data-row="2"><br></td></tr><tr><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3"><br></td></tr><tr><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6"' +
                'class="ql-align-center"><br></td><td data-row="6"><br></td></tr></tbody></table><p>经起草组研究分析，没有与本文件相关联的标准性技术文件及铁总企业标准。<em style="background-color: lime;">（如无相关标准性技术文件/铁总企业标准）</em></p><p>1.3经起草组分析研究，<span style="color: black;">与本文件主要技术内容有关联的</span>现行国家标准、行业标准的关联<span style="color: black;">关系及后续工作建议见表2。</span><em style="color: black; background-color: lime;">（如有相关联的国标、行标）</em></p><p><br></p><p class="ql-align-center">表2 《<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本文件名称）</em>》相关标准评估表</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">被评估标准编号及名称</td><td data-row="1" class="ql-align-center">关联条款</td><td data-row="1" class="ql-align-center">关联性分析</td><td data-row="1" class="ql-align-center">本文件条款的合理性分析</td><td data-row="1" class="ql-align-center">后续工作建议</td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（标准编号）</em><span style="background-color: yellow;">《××××</span><em style="background-color: lime;">（标准名称）</em><span style="background-color: yellow;">》</span></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style=" ' +
                'background-color: lime;">（标准编号）</em>的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>与本文件的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>存在关联</td><td data-row="2"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（关联关系说明）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（条款合理性分析）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（后续工作建议）</em></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td></tr><tr><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3" class="ql-align-center"><em style="background-color: lime;">1</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010《轨道交通 机车车辆牵引变压器和电抗器》</em></td><td data-row="3"><em' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10与本标准第5章存在关联</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10是变压器部件型式试验要求，而本标准第5章包含的是变压器撞车后电力机车作为对象进行的整车温升试验</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准中要求整车试验前完成相关零部件及子系统的型式试验，并应向整车试验单位提交试验报告结果。一般涉及牵引变压器温升的型式试验，即依据GB/T 25120-2010进行，因此，GB/T 25120-2010是本标准试验实施的基础，本标准规定了整车温升试验的工况要求，同时考虑到整车试验的可操作性，可以以车载传感器记录的变压器油温作为参考</em></td><td data-row="3"><em ' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准与GB/T 25120</em></td><td data-row="3"><em style="background-color: lime;">-2010无冲突，GB/T 25120-2010条款无须更改</em></td></tr><tr><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td></tr><tr><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td></tr><tr><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8" class="ql-align-' +
                'center"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td></tr><tr><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td></tr></tbody></table><p><br></p><p>经起草组分析研究，没有与本标准/部分主要技术内容相关联的现行国家标准、行业标准。<em style="background-color: lime;">（如无相关联的国标、行标）</em></p>', //  主要内容
            otherItemsToBeComment: "<p><em style='background-color: lime;'>根据实际情况编写。</em></p>", // 其他应予说明事项
            scplatPrinciple: "<p>1.1&nbsp;标准格式统一、规范，符合<span style='background-color: fuchsia;'>GB/T 1.1—2020</span>要求。</p><p>1.2&nbsp;标准内容符合<span style='color: black;'>统一性、协调性、适用性、一致性、规范性要</span>求。</p><p>1.3&nbsp;标准技术内容<span style='color: black;'>安全可靠、成熟稳定、经</span>济适用、科学先进、节能环保。</p><p>1.4&nbsp;标准实施后有利于提高铁路产品质量、保障运输安全，符合铁路行业发展需求。</p>", // 编制原则
            workBrief: "<p><strong>1.1&nbsp;编制依据</strong></p><p>	根据<span style='background-color: yellow;'>XXXXX</span>通知的要求，由<span style='background-color: fuchsia;'>技术中心科技管理部归口</span>，<span style='color: black;'>并</span>由<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）、</em><span " +
                "style='background-color: yellow;'>……</span>共同起草。</p><p>	<u>本文件</u>为首次制定。<em style='background-color: lime;'>（新制定标准应有本段内容）</em></p><p>	<u>本文件</u>是对<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准编号和名称，编号加年代号）</em>的修订。/<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准1编号和名称）、</em><span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准2编号和名称）、</em><span style='background-color: yellow;'>……</span>的整合修订。<em style='background-color: lime;'>（修订标准应根据实际情况确定本段内容）</em></p><p><strong>1.2&nbsp;制修订本标准的必要性</strong></p><p>	<span style='background-color: yellow;'>……</span>。<em style='background-color: lime;'>（此" + "处给出制修订本标准必要性的说明）</em></p><p><strong>1.3&nbsp;编制过程</strong></p><p>	在<u>本文件</u>的编制过程中，完成了大量的基础研究和编写工作，并邀请了国内和铁路行业相关领域的专家进行了技术审查，确保了标准的规范性和权威性。<u>本文件</u>编制过程概要如下<em style='background-color: lime;'><u>(适用于报批稿)</u></em>：</p><p>	<em style='background-color: lime;'>（编制过程说明至少包括征求意见稿、送审稿、审查会会议纪要、报批稿等四个阶段，根据实际情况增加工作组、送审二稿等阶段）</em></p><p>	（1）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>工作大纲、草案阶段，如有］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em " +
                "style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，形成了工作大纲和<u>本文件</u>的草案稿。</p><p>	（2）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段</em><span style='background-color: lime;'>，</span><em style='background-color: lime;'>有工作大纲和草案阶段的编写本段内容］</em>标准起草组<span style='color: black;'>对前期工作和标准草案深入讨论研究后，</" + "span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段，没有工作大纲和草案阶段的编写本段内容］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，在对<span style='color: black;'>前期工作深入讨论研究后，</span><span style='background-color: yellow;'>××××</span>年" +
                "<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	（3）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿阶段</em><span style='background-color: lime;'>］</span>征求意见过程中，共收到<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（回函单位数量）</em>个单位的回函，其中有反馈意见的单位<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（反馈意见单位数量）</em>个，收到意见<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（意见条数）</em>条。标准起草组对回函的意见进行研究和讨论，逐条进行了处理，对<u>本文件</u>进行修改完善，并组织相关单位进行讨论，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了本文件的送审稿并发送<span style='background-color: fuchsia;'>项目组</span>。</p><p>	（4）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。审查会议无意见分歧，会议通过了<u>本文件</u>的审查。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: " +
                "yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。除<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等技术内容外，审查会议无意见分歧，会议要求起草组对<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（技术问题）</em>等技术内容进一步研究。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	（5）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容，如有更多送审稿别，参考此段增加内容</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的送审二稿，并于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月召开了送审二稿审查会。审查会议无意见分歧，会议通过了送审二稿的审查，<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿如未通过，根据情况增加送审N稿内容</em><span style='background-color: lime;'>］</span></p><p>	（6）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>报批稿阶段</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的报批稿并发送<span style='background-color: fuchsia;'>项目组，由项目组</span>上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>。</p>", // 工作简况
        },
        scplatMode: null, // 制修订模式（0:新编；1:修订）
        stdDraftUrl: null, // 草案稿url地址
        infoPublishId: null, // 信息发布id
        oldStdNo: null, // 修订标准编号 
        oldStdId: null, // 修订标准ID
        stdDraftDeadline: null, //草案稿计划完成时间
        stdForAdviceDeadline: null, // 征求意见稿计划完成时间
        stdForApprovalDeadline: null, // 报批稿计划完成时间
        stdForReviewDeadline: null, // 送审稿计划完成时间
        stdMultiAggreementDeadline: null, // 会签计划完成时间

    },
    // 外部立项数据据模型(内部/企业) (含内置数据)
    applyPorjectEXForm: {
        applyReason: "<p><em>应从以下6方面阐述：</em></p><p><em>1)项目的功能和应用介绍；</em></p> <p><em>2) 发现的问题或不足；</em></p> <p><em>3) 是否有相关的课题，及该课题的进度和成果；</em></p> <p><em>4)相关的国内外标准现状，若有，需列出已知的相关标准；</em></p> <p><em>5) 分析说明现有标准不能满足要求；</em></p> <p><em>6) 已经完成的相关工作及制定标准已具备的条件。</em></p>", // 申请理由
        commitStatus: null, // 提交状态 1：暂存，2：提交
        internationalStandardNameAdopted: null, // 国际标准采标名称
        internationalStandardNoAdopted: null, // 国际标准采标号
        keyTechniqueContent: "<p><em>必须包含以下内容：</em></p><p><br></p><p><em>1)&nbsp;&nbsp;&nbsp; 适用范围说明；</em></p><p><br></p><p><em>标准内容大纲（应包含重点技术内容）。</em></p>", // 关键技术内容
        mainEditorIds: null, // 主要起草人 多个用逗号分隔
        projectName: null, // 项目名称
        projectType: null, // 项目类型（1:企业标准立项；2:外部标准立项；3:企业标准特殊立项）
        scheduledEndTime: null, // 计划结束时间
        scheduledEndTime: null, // 计划开始时间
        scpStdComment: { // 编制说明
            bigIssues: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", //重大分歧意见
            internationStandardAdopt: "<p>	<em style='background-color: lime;'>根据实际情况编写。</em></p>", // 采标情况
            keyIndicator: "<p>1.<span style='background-color: yellow;'>××××</span></p><p>2.<span style='background-color: yellow;'>××××</span></p><p>3.<span style='background-color: yellow;'>××××</span></p><p><span style='background-color: yellow;'>……</span></p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>制定标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键指标或要求（不少于3个）的制定依据、具体指标说明</em></p><p>	<em style='background-color: lime;'>示例：在对高速铁路CZ道岔尖轨、心轨跟端性能要求及试验方法进行充分调研、试验验证的基础上，对尖轨、心轨跟端疲劳试验方法、载荷值做出了规定，提出了经2×10</em><sup style='background-color: lime;'><em>6</em></sup><em style='background-color: lime;'>次循环加载后不应断裂的要求。</em></p><p>	</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>修订标准</em><span style='background-color: lime;'>］</span><em style='background-color: lime;'>关键技术性修订（不少于3个）的修订理由和依据，包括原标准错误或不适用要求的修订。</em></p><p>	<em style='background-color: lime;'>示例1：依据《铁路大型养路机械 通用技术条件》（GB/T 25337-2018）、《铁路大型养路机械 检查与试验方法》（GB/T 25336-2018）等国家标准，结合钢轨铣磨车在我国铁路线路养护维修中的实际应用经验，提出了钢轨铣磨车最大作业速度应大于或等于1.2km/h、一遍作业轨面最大铣削深度应大于或等于1.5mm，轨侧最大铣削深度应大于或等于3 mm的技术要求，以及相应的检验方法。</em></p><p>	<em style='background-color: lime;'>示例2：根据交流传动电力机车网侧谐波分布特点，在对各型交流传动机车等效干扰电流、综合电流畸变率计算方法充分调研分析的基础上，修改了等效干扰电流和综合电流畸变率计算中的谐波电流次数，其中等效干扰电流由计算至30次谐波修改为60次谐波，综合电流畸变率由计算至30次谐波修改为100次谐波。</em></p><p>	<em style='background-color: lime;'>示例3：参考《铁路应用 轮对和转向架 车轮 产品要求》（EN 13262:2004），增加了车轮疲劳性能要求“辐板径向试验应力为±240 N/mm</em><sup style='background-color: lime;'><em>2</em></sup><em style='background-color: lime;'>、经过10</em><sup style='background-color: lime;'><em>7</em></sup><em style='background-color: lime;'>次循环后车轮不应产生裂纹”以及相应的试验方法。</em></p><p><em style='background-color: lime;'>示例4：在总结分析我国混凝土桥、钢梁桥钢轨伸缩调节器的应用经验基础上，本标准提出了客货共线铁路钢轨伸缩调节器基本轨伸缩阻力不应大于50kN、尖轨伸缩阻力不应小于100kN，既能保证基本轨伸缩自如，又能保证调节器轨距变化不超过允许值。</em></p>", // 关键指标确定
            mainContent: '<p>1.1<u>本文件</u>规定了<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致，列出具体内容）</em>；适用于<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（与标准第1章一致）</em>。</p><p>1.2<u>本文件</u><span style="background-color: yellow;">依据××××《××××</span><em style="background-color: lime;">（国际标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（国家标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（行业标准编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: yellow;">，参考</em><span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）</em><span style="background-color: yellow;">》、××××《××××</span><em style="background-color: lime;">（其他规范性文件编号名称）</em><span style="background-color: yellow;">》</span><em style="background-color: lime;">（例如铁总暂行技术条件、国外标准）</em><span style="background-color: yellow;">等技术规范</span><em style="background-color: yellow;">，</em>结合应用实际编制。</p><p>	<u>本文件</u>与<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（标准性技术文件编号名称）</em><span style="background-color: yellow;">》</span>/<span style="background-color: yellow;">××××《××××</span><em style="background-color: lime;">（铁总企业标准编号名称）' + '</em><span style="background-color: yellow;">》</span>相比，重要技术差异见表1。<em style="background-color: lime;">（如有相关标准性技术文件/铁总企业标准）</em></p><p class="ql-align-center">表1 与<span style="background-color: yellow;">××××(</span><em style="background-color: lime;">标准性技术文件或企业标准<u>名称</u>)</em>的重要技术差异</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">标准性技术文件/</td><td data-row="1" class="ql-align-center"><span style="background-color: yellow;">铁总企业标准</span></td><td data-row="1" class="ql-align-center">本文件</td><td data-row="1" class="ql-align-center">说明</td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: ' +
                'lime;">（文件章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本标准章条号及技术内容）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（技术差异说明）</em></td><td data-row="2"><br></td></tr><tr><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3" class="ql-align-center"><br></td><td data-row="3"><br></td></tr><tr><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4" class="ql-align-center"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5" class="ql-align-center"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6" class="ql-align-center"><br></td><td data-row="6"' +
                'class="ql-align-center"><br></td><td data-row="6"><br></td></tr></tbody></table><p>经起草组研究分析，没有与本文件相关联的标准性技术文件及铁总企业标准。<em style="background-color: lime;">（如无相关标准性技术文件/铁总企业标准）</em></p><p>1.3经起草组分析研究，<span style="color: black;">与本文件主要技术内容有关联的</span>现行国家标准、行业标准的关联<span style="color: black;">关系及后续工作建议见表2。</span><em style="color: black; background-color: lime;">（如有相关联的国标、行标）</em></p><p><br></p><p class="ql-align-center">表2 《<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（本文件名称）</em>》相关标准评估表</p><table><tbody><tr><td data-row="1" class="ql-align-center">序号</td><td data-row="1" class="ql-align-center">被评估标准编号及名称</td><td data-row="1" class="ql-align-center">关联条款</td><td data-row="1" class="ql-align-center">关联性分析</td><td data-row="1" class="ql-align-center">本文件条款的合理性分析</td><td data-row="1" class="ql-align-center">后续工作建议</td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td><td data-row="1"><br></td></tr><tr><td data-row="2" class="ql-align-center"><br></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（标准编号）</em><span style="background-color: yellow;">《××××</span><em style="background-color: lime;">（标准名称）</em><span style="background-color: yellow;">》</span></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style=" ' +
                'background-color: lime;">（标准编号）</em>的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>与本文件的<span style="background-color: yellow;">××××</span><em style="background-color: lime;">（章条号）</em>存在关联</td><td data-row="2"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（关联关系说明）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（条款合理性分析）</em></td><td data-row="2" class="ql-align-center"><span style="background-color: yellow;">××××</span><em style="background-color: lime;">（后续工作建议）</em></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td><td data-row="2"><br></td></tr><tr><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3" class="ql-align-center"><em style="background-color: lime;">1</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010《轨道交通 机车车辆牵引变压器和电抗器》</em></td><td data-row="3"><em' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10与本标准第5章存在关联</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">GB/T 25120-2010的10.2.10是变压器部件型式试验要求，而本标准第5章包含的是变压器撞车后电力机车作为对象进行的整车温升试验</em></td><td data-row="3"><em style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准中要求整车试验前完成相关零部件及子系统的型式试验，并应向整车试验单位提交试验报告结果。一般涉及牵引变压器温升的型式试验，即依据GB/T 25120-2010进行，因此，GB/T 25120-2010是本标准试验实施的基础，本标准规定了整车温升试验的工况要求，同时考虑到整车试验的可操作性，可以以车载传感器记录的变压器油温作为参考</em></td><td data-row="3"><em ' +
                'style="background-color: lime;">示例：</em></td><td data-row="3"><em style="background-color: lime;">本标准与GB/T 25120</em></td><td data-row="3"><em style="background-color: lime;">-2010无冲突，GB/T 25120-2010条款无须更改</em></td></tr><tr><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td><td data-row="4"><br></td></tr><tr><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td><td data-row="5"><br></td></tr><tr><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td><td data-row="6"><br></td></tr><tr><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td><td data-row="7"><br></td></tr><tr><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8" class="ql-align-' +
                'center"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td><td data-row="8"><br></td></tr><tr><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td><td data-row="9"><br></td></tr></tbody></table><p><br></p><p>经起草组分析研究，没有与本标准/部分主要技术内容相关联的现行国家标准、行业标准。<em style="background-color: lime;">（如无相关联的国标、行标）</em></p>', //  主要内容
            otherItemsToBeComment: "<p><em style='background-color: lime;'>根据实际情况编写。</em></p>", // 其他应予说明事项
            scplatPrinciple: "<p>1.1&nbsp;标准格式统一、规范，符合<span style='background-color: fuchsia;'>GB/T 1.1—2020</span>要求。</p><p>1.2&nbsp;标准内容符合<span style='color: black;'>统一性、协调性、适用性、一致性、规范性要</span>求。</p><p>1.3&nbsp;标准技术内容<span style='color: black;'>安全可靠、成熟稳定、经</span>济适用、科学先进、节能环保。</p><p>1.4&nbsp;标准实施后有利于提高铁路产品质量、保障运输安全，符合铁路行业发展需求。</p>", // 编制原则
            workBrief: "<p><strong>1.1&nbsp;编制依据</strong></p><p>	根据<span style='background-color: yellow;'>XXXXX</span>通知的要求，由<span style='background-color: fuchsia;'>技术中心科技管理部归口</span>，<span style='color: black;'>并</span>由<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）、</em><span " +
                "style='background-color: yellow;'>……</span>共同起草。</p><p>	<u>本文件</u>为首次制定。<em style='background-color: lime;'>（新制定标准应有本段内容）</em></p><p>	<u>本文件</u>是对<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准编号和名称，编号加年代号）</em>的修订。/<span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准1编号和名称）、</em><span style='background-color: yellow;'>××××-××××《××××》</span><em style='background-color: lime;'>（标准2编号和名称）、</em><span style='background-color: yellow;'>……</span>的整合修订。<em style='background-color: lime;'>（修订标准应根据实际情况确定本段内容）</em></p><p><strong>1.2&nbsp;制修订本标准的必要性</strong></p><p>	<span style='background-color: yellow;'>……</span>。<em style='background-color: lime;'>（此" + "处给出制修订本标准必要性的说明）</em></p><p><strong>1.3&nbsp;编制过程</strong></p><p>	在<u>本文件</u>的编制过程中，完成了大量的基础研究和编写工作，并邀请了国内和铁路行业相关领域的专家进行了技术审查，确保了标准的规范性和权威性。<u>本文件</u>编制过程概要如下<em style='background-color: lime;'><u>(适用于报批稿)</u></em>：</p><p>	<em style='background-color: lime;'>（编制过程说明至少包括征求意见稿、送审稿、审查会会议纪要、报批稿等四个阶段，根据实际情况增加工作组、送审二稿等阶段）</em></p><p>	（1）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>工作大纲、草案阶段，如有］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em " +
                "style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，形成了工作大纲和<u>本文件</u>的草案稿。</p><p>	（2）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段</em><span style='background-color: lime;'>，</span><em style='background-color: lime;'>有工作大纲和草案阶段的编写本段内容］</em>标准起草组<span style='color: black;'>对前期工作和标准草案深入讨论研究后，</" + "span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>征求意见稿阶段，没有工作大纲和草案阶段的编写本段内容］</em>标准计划下达后，在归口单位指导下，<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位1名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位2名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（起草单位3名称）</em><em style='background-color: yellow;'>、</em><span style='background-color: yellow;'>……</span>等单位成立了标准起草组，对<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等情况进行了调研，收集了相关技术资料，在对<span style='color: black;'>前期工作深入讨论研究后，</span><span style='background-color: yellow;'>××××</span>年" +
                "<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的征求意见稿并发送<span style='background-color: fuchsia;'>项目组</span>，由<span style='background-color: fuchsia;'>项目组</span>审查后上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>，征求意见稿发往公司各相关部门进行<span style='color: black;'>意见征集</span>。</p><p>	（3）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿阶段</em><span style='background-color: lime;'>］</span>征求意见过程中，共收到<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（回函单位数量）</em>个单位的回函，其中有反馈意见的单位<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（反馈意见单位数量）</em>个，收到意见<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（意见条数）</em>条。标准起草组对回函的意见进行研究和讨论，逐条进行了处理，对<u>本文件</u>进行修改完善，并组织相关单位进行讨论，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了本文件的送审稿并发送<span style='background-color: fuchsia;'>项目组</span>。</p><p>	（4）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。审查会议无意见分歧，会议通过了<u>本文件</u>的审查。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: " +
                "yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容</em><span style='background-color: lime;'>］</span><span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日，在<span style='background-color: yellow;'>××</span><em style='background-color: lime;'>（城市名称）</em>召开<u>本文件</u>送审稿审查会，会议对送审稿进行了认真讨论。除<span style='background-color: yellow;'>××××、××××、××××……</span><em style='background-color: lime;'>（技术问题1、技术问题2、技术问题3、……）</em>等技术内容外，审查会议无意见分歧，会议要求起草组对<span style='background-color: yellow;'>××××</span><em style='background-color: lime;'>（技术问题）</em>等技术内容进一步研究。<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	（5）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿审查未通过编写本段内容，如有更多送审稿别，参考此段增加内容</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的送审二稿，并于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月召开了送审二稿审查会。审查会议无意见分歧，会议通过了送审二稿的审查，<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月<span style='background-color: yellow;'>××</span>日由<span style='background-color: fuchsia;'>项目组</span>发送了会议纪要（<span style='background-color: yellow;'>文号</span>）。</p><p>	<span style='background-color: lime;'>［</span><em style='background-color: lime;'>送审稿如未通过，根据情况增加送审N稿内容</em><span style='background-color: lime;'>］</span></p><p>	（6）<span style='background-color: lime;'>［</span><em style='background-color: lime;'>报批稿阶段</em><span style='background-color: lime;'>］</span>标准起草组和归口单位按审查会提出的修改意见进行了修改完善，于<span style='background-color: yellow;'>××××</span>年<span style='background-color: yellow;'>××</span>月形成了<u>本文件</u>的报批稿并发送<span style='background-color: fuchsia;'>项目组，由项目组</span>上报<span style='background-color: fuchsia;'>技术中心科技管理部</span>。</p>", // 工作简况
        },
        scplatMode: null, // 制修订模式（0:新编；1:修订）
        stdDraftDeadline: null, //草案稿计划完成时间
        stdDraftUrl: null, // 草案稿url地址
        stdForAdviceDeadline: null, // 征求意见稿计划完成时间
        stdForApprovalDeadline: null, // 报批稿计划完成时间
        stdForReviewDeadline: null, // 送审稿计划完成时间
        stdMultiAggreementDeadline: null, // 会签计划完成时间
        stdType: null, // 标准类型
        infoPublishId: null, // 信息发布id
        oldStdNo: null, // 修订标准编号 
        oldStdId: null, // 修订标准ID
        ownerDeptId: null, // 归口单位id
        attachFiles: null, // 附件
    },

}